# Generated by Django 4.1.5 on 2023-07-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=100)),
                ('ephone', models.CharField(max_length=10)),
                ('eemail', models.EmailField(max_length=254, unique=True)),
                ('edepartment', models.CharField(max_length=20)),
            ],
        ),
    ]
