# Generated by Django 4.1.5 on 2023-07-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='edepartment',
            field=models.CharField(max_length=20, verbose_name='edepartment'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eemail',
            field=models.EmailField(max_length=254, verbose_name='eemail'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='eid'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ename',
            field=models.CharField(max_length=100, verbose_name='ename'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ephone',
            field=models.CharField(max_length=10, verbose_name='ephone'),
        ),
    ]
