# Generated by Django 4.1.5 on 2023-07-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_edepartment_alter_employee_eemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ephone',
            field=models.IntegerField(max_length=10, verbose_name='ephone'),
        ),
    ]
