# Generated by Django 4.1.5 on 2023-07-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_eemail_alter_employee_ephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eemail',
            field=models.EmailField(max_length=254, verbose_name='eemail'),
        ),
    ]
