# Generated by Django 4.1.5 on 2023-07-10 06:02

import django.core.validators
from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_eemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eemail',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Invalid email address.')], verbose_name='eemail'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ephone',
            field=models.IntegerField(max_length=15, validators=[employees.models.validate_ephone], verbose_name='ephone'),
        ),
    ]
